### ISSUE TITLE
NSIS not replacing all placeholder strings

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-packaging#1]
Hi @mbrunettini,

after further investigations related to https://github.com/robotology/wysiwyd/issues/22, I found the problem which causes the issues. The problem is not related to AppVeyor, but happens on all Windows platforms.

Here is what happens:
1) cmake includes `icub-1.1.16/cmake/icub-config.cmake`
2) In `icub-1.1.16/cmake/icub-config.cmake`, cmake is asked to `include("${ICUB_INSTALLED_LOCATION}/lib/ICUB/icub-export-install.cmake")` (which can be successfully done, because `ICUB_INSTALLED_LOCATION` is replaced with the proper path by NSIS)
3) In `icub-1.1.16/lib/ICUB/icub-export-install.cmake`, cmake is asked to include all files matching `icub-export-install-*.cmake` (see # Load information for each installed configuration.)
4) This includes the files `icub-config-fp.cmake`, `icub-export-install-debug-fp.cmake`, `icub-export-install-includes-fp.cmake` and `icub-export-install-release-fp.cmake` where the `_NSIS_` placeholders are not replaced, and therefore the wrong paths are loaded.
5) Then, back in `icub-1.1.16/cmake/icub-config.cmake`, the following command fails because `ICUB_INSTALLED_LOCATION` is set incorrectly: `include("${ICUB_INSTALLED_LOCATION}/lib/ICUB/icub-export-install-includes.cmake")`

It would be great if you fix this. I am not sure what the `*-fp.cmake` files are good for, but those are the ones causing the troubles. As soon as we delete them, we are able to build `wysiwyd` successfully. I guess in previous releases of `icub-main`, these files were either non-existing, or the nsis stuff was handled differently.

Thanks,
Tobias

**Comment by mbrunettini** [comment]
All the `*-fp.cmake` files are temporary files produced in the package building process and should not be included in the binary package.
Fixed in the next package rebuild release.

**Comment by Tobias-Fischer** [comment]
Great, thank you. Can you estimate when you will next rebuild the packages?

**Comment by pattacini** [comment]
Reminder: once the new package is out, we can get rid of the patch inside appveyor script.

**Comment by Tobias-Fischer** [comment]
A few more issues to be actually able to compile wysiwyd.
Firstly, you also need to remove `icub-export-install-debug.cmake` and `icub-export-install-release.cmake`. Secondly, in `icub-export-install-includes.cmake`, paths are not correctly substituted by nsis. There are some `E:\cygwin\...` paths in there, which need to be removed.

**Comment by lornat75** [comment]
This may be related to this:
https://github.com/robotology/icub-main/issues/198

@mbrunettini has fixed it. we should rebuild binaries packages so we can test it in the field.

**Comment by drdanz** [comment]
The `icub-export-install-debug.cmake` and `icub-export-install-release.cmake` are necessary, CMake will automatically include them and load all the info for each configuration.

**Comment by Tobias-Fischer** [comment]
@drdanz: Ahh I see. Thanks! Then it must have been the incorrect paths in `icub-export-install-includes.cmake` which also caused trouble. We'll see once the new binaries are released.
@lornat75: Not that I know much of the installer, but it sounds like the issues could be related, yes :).

**Comment by mbrunettini** [comment]
No, it is not related to issue robotology/icub-main#198
