### ISSUE TITLE
GSL path incorrect

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-packaging#12]
Hi,
It seems like https://github.com/robotology/icub-packaging/issues/1 is still an issue. Compiling projects relying on the iCub package fails due to an incorrect path in GSL:
```
       (Link target) -> 
         LINK : fatal error LNK1181: cannot open input file 'E:\Cygwin64\home\icub\icub-packaging\windows\build\gsl-1.14-v14-x86_amd64-Release\lib\gsl.lib' [C:\dev\icub-hri\build\src\modules\tools\referenceFrameHandler\referenceFrameHandler.vcxproj]
```

For more details, see https://ci.appveyor.com/project/robotology/icub-client/builds/23840005

**Comment by mbrunettini** [comment]
fixed
