### ISSUE TITLE
issue while installing ycm-cmake-modules

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-packaging#14]
While generating a Docker container ex-novo, the following commands:
```
RUN echo "deb http://www.icub.org/ubuntu `lsb_release -cs` contrib/science" > /etc/apt/sources.list.d/icub.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 57A5ACB6110576A6
RUN apt update
RUN apt install -y icub-common
```
are currently producing the following error:
```
icub-common: depends: ycm-cmake-modules but it is not going to be installed.
E: Unable to correct problems, you have held broken packages.
```
The same commands were ok one week ago.
What should I check?

**Comment by randaz81** [comment]
I also tried to run `apt upgrade` just before these line, but unsuccessfully.

**Comment by mbrunettini** [comment]
the required package is inside our repository, alogn with icub-common and it should be installed.
I tested the installation and I had no issue.
can you run 
`apt install -f `
after 
` apt install -y icub-common`
and let me know?

**Comment by drdanz** [comment]
I think that you also have to enable the kitware cmake repository, for cmake >3.12, or ycm will not install

**Comment by randaz81** [comment]
fixed editing the Dockerfile to install `cmake 3.12` BEFORE `ycm-cmake-module`.

**Comment by mbrunettini** [comment]
solved by installing required CMake version.
Packaged have been updated adding minimum Cmake required version
