### ISSUE TITLE
Is anything from this repo still used?

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-packaging#18]
If we are not anything from this repo anymore, we can probably clarify this in the readme and archive it. @Nicogene @pattacini

**Comment by pattacini** [comment]
Fine with me 👍🏻 
cc'ing @mbrunettini too.

**Comment by mbrunettini** [comment]
Thanks @pattacini !
Fine with me too 👍

**Comment by Nicogene** [comment]
Ok for archiving it!

**Comment by pattacini** [comment]
I can archive the repo.
Before that, do you think we can point to other resources in the message we put in the README?

**Comment by pattacini** [comment]
Do you think that the message below is ok?

>⚠ This repository has been archived as the packaging is now managed via the [`robotology-superbuild`](https://github.com/robotology/robotology-superbuild) infrastructure.

**Comment by traversaro** [comment]
Ok!

**Comment by pattacini** [comment]
Done!
