### ISSUE TITLE
URL of Windows installer was wrong in documentation

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-packaging#2]
I fixed it in http://wiki.icub.org/index.php?title=Downloads&diff=21875&oldid=21813 , but I wonder if there is some problem in the process of naming binaries. 

cc @mbrunettini @lornat75

**Comment by mbrunettini** [comment]
No, we simply did a new repackaging, without updating the wiki page.
Thanks for fixing it.
Issue closed.
