### ISSUE TITLE
Problems with Windows binaries in Debug

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-packaging#4]
@Anouk92 commented on [Wed Aug 24 2016](https://github.com/robotology/QA/issues/133)

When I try to run this [_castesian-interface code_](https://github.com/lornat75/Teaching/tree/master/code/cartesian-interface) for the icub simulation that is provided from within the [**Teaching**](https://github.com/lornat75/Teaching) repository on GitHub, I get the following exception: 

```
"Unhandled exception at 0x00D831CA (msvcr120d.dll) in cartesian-interface.exe: 0xC0000005: Access violation reading location 0xBA006574."
```

The program breaks in the code on the following line: [`if (!client.open(option))`](https://github.com/lornat75/Teaching/blob/master/code/cartesian-interface/src/main.cpp#L70)

The system I use is:
- Windows 10
- yarp 2.3.66 v12 x86
- iCub 1.4.0 v12 x86
- CMake 3.6.1 x86
- Visual Studio 12 2013, also 32 bits

Can someone tell me what I need to do to get the code running?

Thanks!

---

@pattacini commented on [Wed Aug 24 2016](https://github.com/robotology/QA/issues/133#issuecomment-242067722)

Hi @Anouk92 and welcome on board :smile: 

I've just tried out that code on my `Windows 10` with `Visual Studio 2013` and `yarp/devel` + `iCub/master` compiled at `32-bit` from sources. No problems spotted. The only significant difference I see is then that you used `yarp` and `iCub` pre-compiled binaries.

The exception you got indicates that there's a **memory safety violation**, which is in turn likely due to a [_dangling pointer_](https://en.wikipedia.org/wiki/Dangling_pointer). Given that the [`open`](https://github.com/robotology/icub-main/blob/master/src/libraries/icubmod/cartesianController/ClientCartesianController.cpp#L90) method of the client doesn't allocate and/or reference explicitly any memory location via pointers (as far as I see, at least), I would believe the failure might be caused by `yarp` calls themselves.

Therefore, did you already check the **integrity of your installation**? In other words, a possibility would be also to run a different, simpler [**tutorial**](https://github.com/robotology/icub-tutorials/tree/master/src/motorControlBasic), which does some basic operations with ports and motor interfaces.

Would you mind reporting on the results you'll get with that test?

---

@Anouk92 commented on [Thu Aug 25 2016](https://github.com/robotology/QA/issues/133#issuecomment-242313164)

Thank you for your response!
I've tried several other tutorials, also the one you showed, and most of them seem to work. However, when trying the run the gaze-interface tutorial, I found that I could run the 'mover' project fine but the 'tracker' object gave the same exception: 

```
"Unhandled exception at 0x016731CA (msvcr120d.dll) in tracker.exe: 0xC0000005: Access violation reading location 0xBA006574."
```

Now the code breaks at line 58: 'if (!clientGaze.open(optGaze))', so again at the open method of the client.

---

@pattacini commented on [Thu Aug 25 2016](https://github.com/robotology/QA/issues/133#issuecomment-242350885)

I and @Anouk92 had a debug stint, finding that the run-time failure is caused by a mismatch between the user code compiled in `Debug` and the `yarp` + `iCub` binaries shipped in `Release` (most likely).
In fact, **the same tutorial compiled in `Release` runs just fine**.

@mbrunettini @drdanz are these considerations correct?
- [ ] Are _Windows_ **pre-compiled binaries actually distributed in `Release`**?
- [ ] Is there any **recommendation in the wiki** warning users to compile their code in `Release` mode while linking against those packages?

**Comment by drdanz** [comment]
As far as I know, both Release and Debug configurations are shipped with the binary packages...

**Comment by pattacini** [comment]
@drdanz I had a quick inspection in @Anouk92 's system and I didn't seem to find any `Debug` configuration. I'm not 100% sure though.

Btw, @Anouk92 is with us these days: she's sitting by @hagenlehmann

cc @mbrunettini

**Comment by pattacini** [comment]
It came out that both `Release` and `Debug` configurations are available from binary packages, but `msvcr120d.dll` is not shipped although is required.

**Comment by drdanz** [comment]
`msvcr120d.dll` is not redistributable (only the `release` dlls are) and comes with MSVC.
We found out that the package was (probably) built with MSVC 12 2013 Update **5**, while @Anouk92 is running the Update **4** on her computer, so that might be the reason why the dll is causing this `Unhandled exception`.

**Comment by pattacini** [comment]
Shall we close this then?

**Comment by Anouk92** [comment]
I'm updating visual studio now to Update 5, I'll let you know when it's done whether the Debug works

**Comment by drdanz** [comment]
Let's wait for @Anouk92 ... Also we should add this information somewhere...

**Comment by pattacini** [comment]
@drdanz agreed :+1:

**Comment by Anouk92** [comment]
Unfortunately the update didn't help, I still get the exception when running in Debug mode. In Release mode it does work.

**Comment by mbrunettini** [comment]
I confirm, both of them are shipped with binary packages.
Which release version has been downloaded?

**Comment by lornat75** [comment]
Are we sure it is a DLL conflict causing this problem? The fact that the problem appears only in `Debug` mode is not an indication that the problem is a DLL conflict. Has any of us tried to reproduce the problem?

**Comment by drdanz** [comment]
The release dll is shipped with the yarp package, while the debug dll is not redistributable and is installed with MSVC. That's why the DLL conflict looks plausible... I just checked on @Anouk92 computer and both the dlls (debug and release) are now the exact same version, so I run out of ideas...
If anyone could try and reproduce the issue it would be useful...

**Comment by pattacini** [comment]
Microsoft made [freely available **Windows 7/8/10 VM**](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). I've just downloaded and imported a **Win10 VM**: it works great (see below).

![capture](https://cloud.githubusercontent.com/assets/3738070/18102799/357620de-6ef4-11e6-8f75-467751a299a1.PNG)

My idea is then to use it for testing this issue in background. Stay tuned.

**Comment by pattacini** [comment]
cc @vtikha

**Comment by pattacini** [comment]
#### Update

Using the VM I managed to test that with dependencies installed and `yarp` + `icub-main` compiled in `Debug`, the tutorial runs fine.

Next step would be to test if `yarp` + `icub-main` installed will give the same positive result.

@mbrunettini 
Btw I think I can share with you my **VM**. It's an **Hyper-V** compatible VM, but with [**StarWind V2V converter**](https://www.starwindsoftware.com/converter) I believe I can provide it in different formats (e.g. VmWare).

**Comment by pattacini** [comment]
I replicated the same @Anouk92's conditions in my **VM** and I got the same failure in `Debug`.

Given that we're distributing binaries produced likely with `Ultimate` edition, while we're testing against `Express`, I'll perform further tests with the following 3 DLL in `Ultimate` mode:
- `msvcp120d.dll`
- `msvcr120d.dll`
- `vccorlib120d.dll`

**Comment by pattacini** [comment]
@mbrunettini hold on, I might have them myself...

**Comment by mbrunettini** [comment]
Sure I Will.
But note that we do not distribuite DEBUG DLL because we are not allowed to.

**Comment by pattacini** [comment]
Yep indeed, they get installed once Visual Studio Express is installed.

Unfortunately, the last test failed as well...

**Comment by pattacini** [comment]
Unfortunately, the last test failed as well...

**Comment by pattacini** [comment]
### Wrap-up

After having _installed dependencies_ by means of our packages, we're given two cases:
1. `yarp` and `icub-main` **compiled from sources in `Debug`**.
2. `yarp` and `icub-main` **installed from binaries**.

Then:
- In **case 1**, the tutorial **runs smoothly**.
- In **case 2**, the tutorial **fails to start** with the error reported above. Testing against different DLL did not help.

@drdanz @lornat75 @mbrunettini

**Comment by lornat75** [comment]
https://en.wikipedia.org/wiki/DLL_Hell

:dancers:
