### ISSUE TITLE
icub-common should depend on the libopencv-dev package

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-packaging#9]
Historically the `icub-common` package depended on the three packages `libhighgui-dev`, `libcv-dev` and `libcvaux-dev`
(see https://github.com/robotology/icub-packaging/blob/6a7c28363f6a05fddf4adbded02224231a32d1dd/linux/config.sh#L18). However it new distributions such as Ubuntu 18.04 this packages seems to have been substituted by the `libopencv-dev` package, but `icub-common` does not depend on the `libopencv-dev` package. 
Would it make sense to make `icub-common` depend on `libopencv-dev` ? 
See related discussion: https://github.com/robotology/robotology-superbuild/issues/56 . 

cc @mbrunettini @pattacini @vtikha

**Comment by pattacini** [comment]
Agree on that 👍

**Comment by mbrunettini** [comment]
the new release has the following dependencies

```
ICUB_DEPS_COMMON="libace-dev libc6 python libgsl0-dev libncurses5-dev libsdl1.2-dev subversion git gfortran cmake libxmu-dev libode-dev wget unzip qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev libqt5svg5 libqt5opengl5-dev libopencv-dev freeglut3-dev libtinyxml-dev libblas-dev coinor-libipopt-dev liblapack-dev libmumps-dev qml-module-qtmultimedia qml-module-qtquick-dialogs qml-module-qtquick-controls libedit-dev libeigen3-dev libjpeg-dev libsimbody-dev"
ICUB_DEPS_bionic="libode6"
ICUB_DEPS_cosmic="libode6"
ICUB_DEPS_disco="libode8"
ICUB_DEPS_stretch="libode6 libhighgui-dev libcv-dev libcvaux-dev"
```

for each distribuition
`ICUB_DEPS=ICUB_DEPS_COMMMON & ICUB_DEPS_distro-name`

what do you think?

**Comment by traversaro** [comment]
As `libopencv-dev`  is available in stretch, there is any specific reason for also installing `libhighgui-dev libcv-dev libcvaux-dev` in stretch?

**Comment by mbrunettini** [comment]
ok, `removed libhighgui-dev libcv-dev libcvaux-dev` from stretch in 1.13
